USE accountbook;
CREATE TABLE config(
id INT PRIMARY KEY AUTO_INCREMENT,
plan FLOAT(6,1),
site VARCHAR(20)
)ENGINE=INNODB,CHARSET=UTF8;

CREATE TABLE category(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20)
)ENGINE=INNODB,CHARSET=UTF8;

CREATE TABLE account(
id INT PRIMARY KEY AUTO_INCREMENT,
cid INT,
FOREIGN KEY(cid) REFERENCES category(id),
amount FLOAT(6,1),
note VARCHAR(255),
use_date TIME
)ENGINE=INNODB,CHARSET=UTF8;